---
# tasks file for roles/initialization
- name: Install Debian
  block:
  
  - name: Install packeg
    apt:
      pkg:
      - wget
      - git

  #- sysctl:
  #    name: fs.files-max
  #    value: '1204000'
  #    state: present
  #    reload: yes
            
  #- sysctl:
  #    name: net.core.somaxconn
  #    value: '65535'
  #    state: present
  #    reload: yes
      
  - name: ssh key Install
    file:
      path: /root/.ssh
      state: directory
  - copy:
      src: authorized_keys
      dest: /root/.ssh
      owner: root
      group: root
      mode: '0644'
  
  when: ansible_os_family == "Debian"