---
# tasks file for install_nginx


- name: Debian
  block:
  - name: Install nginx
    apt:
      pkg:
      - nginx
    

  - name: write the site config file
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
  
  #- file:  
  #    path="{{ dir_for_site }}"
  #    mode=0755
  #    owner=nginx
  #    group=nginx
  #    state=directory

  - name: Clone a github repository
    #shell: git clone "{{ URL_git }}"
    ansible.builtin.git:
      repo: https://github.com/B-e-r-i-ya/site1.git
      dest: /var/www/html/site
      version: master
      clone: yes
      update: yes
  #- copy:
  #    src: ./site1
  #    dest: "{{ dir_for_site }}"
    notify:
      - startup_nginx

  
  when: ansible_os_family == "Debian"